import type { RestaurantResponse, RestaurantStatus } from '../types/restaurant.types';

export const MOCK_RESTAURANTS: RestaurantResponse[] = [
  {
    id: 1,
    name: 'Truffles',
    description: 'American, Burgers, Fast Food',
    cuisineType: 'American',
    address: 'St. Marks Road, Bangalore',
    phone: '9876543210',
    email: 'contact@truffles.com',
    ownerId: 2,
    status: 'APPROVED' as RestaurantStatus,
    isOpen: true,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    deliveryTime: 35,
    costForTwo: 600,
  },
  {
    id: 2,
    name: 'Meghana Foods',
    description: 'Biryani, Andhra, South Indian',
    cuisineType: 'Indian',
    address: 'Koramangala, Bangalore',
    phone: '9876543211',
    email: 'contact@meghanafoods.com',
    ownerId: 2,
    status: 'APPROVED' as RestaurantStatus,
    isOpen: true,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=800&q=80',
    deliveryTime: 40,
    costForTwo: 800,
  },
  {
    id: 3,
    name: 'Leon Grill',
    description: 'Fast Food, Turkish, Arabian',
    cuisineType: 'Arabian',
    address: 'Indiranagar, Bangalore',
    phone: '9876543212',
    email: 'contact@leongrill.com',
    ownerId: 2,
    status: 'APPROVED' as RestaurantStatus,
    isOpen: true,
    rating: 4.2,
    imageUrl: 'https://images.unsplash.com/photo-1606131731446-5568d87113aa?w=800&q=80',
    deliveryTime: 25,
    costForTwo: 500,
  },
  {
    id: 4,
    name: 'Corner House Ice Creams',
    description: 'Desserts, Ice Cream',
    cuisineType: 'Desserts',
    address: 'Jayanagar, Bangalore',
    phone: '9876543213',
    email: 'contact@cornerhouse.com',
    ownerId: 2,
    status: 'APPROVED' as RestaurantStatus,
    isOpen: true,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1559703248-dcaaec9fab78?w=800&q=80',
    deliveryTime: 20,
    costForTwo: 300,
  },
  {
    id: 5,
    name: 'Taco Bell',
    description: 'Mexican, Fast Food',
    cuisineType: 'Mexican',
    address: 'MG Road, Bangalore',
    phone: '9876543214',
    email: 'contact@tacobell.com',
    ownerId: 2,
    status: 'APPROVED' as RestaurantStatus,
    isOpen: true,
    rating: 4.0,
    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&q=80',
    deliveryTime: 30,
    costForTwo: 400,
  },
  {
    id: 6,
    name: 'Empire Restaurant',
    description: 'North Indian, Mughlai',
    cuisineType: 'Indian',
    address: 'Church Street, Bangalore',
    phone: '9876543215',
    email: 'contact@empire.com',
    ownerId: 2,
    status: 'APPROVED' as RestaurantStatus,
    isOpen: false, // Closed right now
    rating: 4.1,
    imageUrl: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?w=800&q=80',
    deliveryTime: 45,
    costForTwo: 700,
  }
];
